name: Run Tests Every 6 hours (Scheduled)

on:
  # Manual trigger for testing
  workflow_dispatch:

  # Run every 6 hours
  schedule:
    - cron: '0 */6 * * *'

jobs:
  smoke-test:
    name: Smoke Tests
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2t64 \
            libglib2.0-0t64 \
            libnss3 \
            libatk1.0-0t64 \
            libatk-bridge2.0-0t64 \
            libcups2t64 \
            libdrm2 \
            libdbus-1-3 \
            libxcb1 \
            libxkbcommon0 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxrandr2 \
            libgbm1 \
            libpango-1.0-0 \
            libcairo2 \
            libatspi2.0-0t64 \
            libx11-6 \
            libffi8

      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Copy environment config
        run: |
          mkdir -p env
          cp env/.env.staging1 env/.env

      - name: Run smoke login tests
        run: npm run test:bdd:tags "@login"
        env:
          CI: true
          TEST_ENV: staging1
          DEFAULT_USERNAME: ${{ secrets.DEFAULT_USERNAME }}
          DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-results-${{ github.run_number }}
          path: |
            test-results/
            cucumber-report.json
            cucumber-report.html
          retention-days: 7